# jekyll config
safe: ture
timezone: 'Etc/UTC'
encoding: 'utf-8'
url: 'https://www.ashenm.ml'

plugins:
  - jekyll-redirect-from

exclude:
  - CNAME
  - Gemfile
  - Makefile
  - README.md

# metadata defaults
lang: 'en'
title: 'Ashen Gunaratne'
author:
  first_name: 'Ashen'
  last_name: 'Gunaratne'
email: 'mail@ashenm.ml'
keywords: 'ashen, gunaratne, ashen gunaratne, ashen m gunaratne, homepage, bio, curriculum vitae, cv, resume'
desc: 'An alumnus of the Harvard John A. Paulson School of Engineering and Applied Sciences of Harvard University'

# front matter defaults
defaults:
  scope:
    path: ''
    type: 'pages'
  values:
    layout: 'default'
