# jekyll config
safe: ture
timezone: 'Etc/UTC'
encoding: 'utf-8'
url: 'https://www.ashenm.ml'

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
exclude:
  - CNAME
  - Gemfile
  - Makefile
  - README.md
  - vendor

# metadata defaults
lang: 'en'
title: 'Ashen Gunaratne'
author:
  first_name: 'Ashen'
  last_name: 'Gunaratne'
email: 'mail@ashenm.ml'
keywords: 'ashen, gunaratne, homepage, bio, curriculum vitae, cv, resume'
desc: 'Ashen Gunaratne is an alumnus of the Harvard John A. Paulson School of Engineering and Applied Sciences of Harvard University'

# front matter defaults
defaults:
  - scope:
      path: ''
      type: 'pages'
    values:
      layout: 'default'
  - scope:
      path: '404'
    values:
      sitemap: false
