- path: example
  url: https://www.example.com/
- path: vault
  url: https://vault.ashenm.ml/
- path: feedback
  url: https://sentiment.ashenm.ml/
- path: github
  url: https://github.com/ashenm
- path: transcripts
  url: https://drive.google.com/drive/folders/1JuSeKGNuvkl8HB4dJEsx1aCf_UsW_17Y?usp=sharing
